// Code generated by reader, DO NOT EDIT.
package examples

import uuid "github.com/google/uuid"

func (b Bar) ID() uuid.UUID {
	return b.id
}

func (b Bar) Name() string {
	return b.name
}

func (b Bar) URL() string {
	return b.url
}
