// Code generated by github.com/alextanhongpin/getter, DO NOT EDIT.

package examples

import uuid "github.com/google/uuid"

func (a Account) ID() int64 {
	return a.id
}

func (a Account) Name() string {
	return a.name
}

func (u User) ID() uuid.UUID {
	return u.id
}

func (u User) FullName() string {
	return u.name
}

func (u User) AccountID() int64 {
	return u.acc.id
}

func (u User) AccountName() string {
	return u.acc.name
}
