// Code generated by access, DO NOT EDIT.
package examples

import "database/sql"

func (f Foo) Name() string {
	return f.name
}

func (f Foo) RealAge() Age {
	return f.realAge
}

func (f *Foo) SetExtra(extra string) *Foo {
	f.Extra = extra
	return f
}

func (f Foo) Hobby() sql.NullString {
	return f.hobby
}

func (f Foo) Tags() []string {
	return f.tags
}

func (f Foo) Permission() *string {
	return f.permission
}

func (f *Foo) SetPermission(permission string, valid bool) *Foo {
	if valid {
		f.permission = &permission
	}
	return f
}
