// Code generated by reader, DO NOT EDIT.
package examples

import "database/sql"

func (f Foo) Name() string {
	return f.name
}

func (f Foo) RealAge() Age {
	return f.realAge
}

func (f Foo) Hobby() sql.NullString {
	return f.hobby
}

func (f Foo) Tags() []string {
	return f.tags
}

func (f Foo) Permission() *string {
	return f.permission
}
