// Code generated by github.com/alextanhongpin/getter, DO NOT EDIT.

package examples

func (i InlinePrefixParent) InlineName() string {
	return i.InlineChildren.Name
}

func (i InlinePrefixParent) InlineAge() int64 {
	return i.InlineChildren.age
}
