// Code generated by accessor, DO NOT EDIT.
package examples

import "database/sql"

func (f Foo) Name() string {
	return f.name
}

func (f *Foo) SetName(name string) {
	f.name = name
}

func (f Foo) Hobby() sql.NullString {
	return f.hobby
}

func (f *Foo) SetHobby(hobby sql.NullString) {
	f.hobby = hobby
}

func (f Foo) Tags() []string {
	return f.tags
}

func (f *Foo) SetTags(tags []string) {
	f.tags = tags
}

func (f Foo) Permission() *string {
	return f.permission
}

func (f *Foo) SetPermission(permission *string) {
	f.permission = permission
}
