// Code generated by github.com/alextanhongpin/getter, DO NOT EDIT.
package examples

func (t TestWalk) Name() string {
	return t.name
}

func (t TestWalk) Age() int {
	return t.age
}

func (t TestWalk) Nested() [int64(3)]Nested {
	return t.nested
}

func (t TestWalk) M1() map[string][]*Nested {
	return t.m1
}

func (t TestWalk) M2() map[string][][int64(3)]*map[string]*Nested {
	return t.m2
}

func (t TestWalk) M3() *Nested {
	return t.m3
}

func (t TestWalk) M4() [int64(100)]map[*Nested][]*map[*string]*Nested {
	return t.m4
}
