// Code generated by github.com/alextanhongpin/getter, DO NOT EDIT.

package examples

import uuid "github.com/google/uuid"

func (u User) GetID() uuid.UUID {
	return u.id
}

func (u User) GetFullName() string {
	return u.name
}

func (u User) GetAccountID() int64 {
	return u.acc.id
}

func (u User) GetAccountName() string {
	return u.acc.name
}
